services:

  core:
    container_name: core
    build: .
    ports:
      - "8000:8000"
    
    volumes:
      - .:/core

    working_dir: /core
    
    command: ["uvicorn", "core.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]