services:

  # database container
  postgres_db:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # project container
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"

    depends_on:
      - postgres_db
    
    volumes:
      - .:/app

    working_dir: /app
    
    command: ["uvicorn", "core.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]



volumes:
  postgres_data: