"""fix: added status column to mechanic reservation model

Revision ID: 84e6626875aa
Revises: fb81c3ec72f3
Create Date: 2025-08-30 08:03:27.030213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e6626875aa'
down_revision: Union[str, Sequence[str], None] = 'fb81c3ec72f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resevations', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resevations', 'status')
    # ### end Alembic commands ###
