"""feat: added rating field to mechanic reservation model

Revision ID: a75f60d6e9ed
Revises: 84e6626875aa
Create Date: 2025-08-31 08:57:07.231430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75f60d6e9ed'
down_revision: Union[str, Sequence[str], None] = '84e6626875aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resevations', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resevations', 'rating')
    # ### end Alembic commands ###
