"""fix: fixed user_id in car model

Revision ID: a878f3283de4
Revises: 7ef93f08adeb
Create Date: 2025-08-25 23:48:51.821229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a878f3283de4"
down_revision: Union[str, Sequence[str], None] = "7ef93f08adeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "cars", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cars", type_="foreignkey")
    op.drop_column("cars", "user_id")
    # ### end Alembic commands ###
