"""feat: added problem and price models

Revision ID: ca859aef498b
Revises: ca8feedc7bf0
Create Date: 2025-11-18 10:38:16.586922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca859aef498b'
down_revision: Union[str, Sequence[str], None] = 'ca8feedc7bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rust', sa.Integer(), nullable=False),
    sa.Column('scratches', sa.Integer(), nullable=False),
    sa.Column('dents', sa.Integer(), nullable=False),
    sa.Column('bad_odor', sa.Integer(), nullable=False),
    sa.Column('strange_noises', sa.Integer(), nullable=False),
    sa.Column('no_cooling', sa.Integer(), nullable=False),
    sa.Column('malfunctioning_lights', sa.Integer(), nullable=False),
    sa.Column('faulty_starter', sa.Integer(), nullable=False),
    sa.Column('dead_battery', sa.Integer(), nullable=False),
    sa.Column('uneven_tire_wear', sa.Integer(), nullable=False),
    sa.Column('wobbling', sa.Integer(), nullable=False),
    sa.Column('misalignment', sa.Integer(), nullable=False),
    sa.Column('vibration_when_braking', sa.Integer(), nullable=False),
    sa.Column('reduced_responsiveness', sa.Integer(), nullable=False),
    sa.Column('squeaking_noises', sa.Integer(), nullable=False),
    sa.Column('grinding_noises', sa.Integer(), nullable=False),
    sa.Column('clutch_slip', sa.Integer(), nullable=False),
    sa.Column('difficulty_shifting', sa.Integer(), nullable=False),
    sa.Column('delayed_acceleration', sa.Integer(), nullable=False),
    sa.Column('transmission_fluid_leak', sa.Integer(), nullable=False),
    sa.Column('harsh_shifting', sa.Integer(), nullable=False),
    sa.Column('oil_leak', sa.Integer(), nullable=False),
    sa.Column('overheating', sa.Integer(), nullable=False),
    sa.Column('low_engine_oil', sa.Integer(), nullable=False),
    sa.Column('weak_battery', sa.Integer(), nullable=False),
    sa.Column('flat_tire', sa.Integer(), nullable=False),
    sa.Column('low_brake_oil', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basic_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('low_engine_oil', sa.Boolean(), nullable=True),
    sa.Column('weak_battery', sa.Boolean(), nullable=True),
    sa.Column('flat_tire', sa.Boolean(), nullable=True),
    sa.Column('low_brake_oil', sa.Boolean(), nullable=True),
    sa.Column('main_problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_problem_id'], ['main_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('dents', sa.Boolean(), nullable=True),
    sa.Column('scratches', sa.Boolean(), nullable=True),
    sa.Column('rust', sa.Boolean(), nullable=True),
    sa.Column('main_problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_problem_id'], ['main_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brake_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('squeaking_noises', sa.Boolean(), nullable=True),
    sa.Column('reduced_responsiveness', sa.Boolean(), nullable=True),
    sa.Column('vibration_when_braking', sa.Boolean(), nullable=True),
    sa.Column('main_problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_problem_id'], ['main_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electrical_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('dead_battery', sa.Boolean(), nullable=True),
    sa.Column('faulty_starter', sa.Boolean(), nullable=True),
    sa.Column('malfunctioning_lights', sa.Boolean(), nullable=True),
    sa.Column('main_problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_problem_id'], ['main_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('havac_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('no_cooling', sa.Boolean(), nullable=True),
    sa.Column('strange_noises', sa.Boolean(), nullable=True),
    sa.Column('bad_odor', sa.Boolean(), nullable=True),
    sa.Column('main_problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_problem_id'], ['main_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_transmission_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_problem_id'], ['main_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motor_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('overheating', sa.Boolean(), nullable=True),
    sa.Column('oil_leak', sa.Boolean(), nullable=True),
    sa.Column('strange_noises', sa.Boolean(), nullable=True),
    sa.Column('main_problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_problem_id'], ['main_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wheel_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('misalignment', sa.Boolean(), nullable=True),
    sa.Column('wobbling', sa.Boolean(), nullable=True),
    sa.Column('uneven_tire_wear', sa.Boolean(), nullable=True),
    sa.Column('main_problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_problem_id'], ['main_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmission_automatic_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('harsh_shifting', sa.Boolean(), nullable=True),
    sa.Column('transmission_fluid_leak', sa.Boolean(), nullable=True),
    sa.Column('delayed_acceleration', sa.Boolean(), nullable=True),
    sa.Column('main_transmission_problem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_transmission_problem'], ['main_transmission_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmission_manual_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('difficulty_shifting', sa.Boolean(), nullable=True),
    sa.Column('clutch_slip', sa.Boolean(), nullable=True),
    sa.Column('grinding_noises', sa.Boolean(), nullable=True),
    sa.Column('main_transmission_problem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_transmission_problem'], ['main_transmission_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transmission_manual_problems')
    op.drop_table('transmission_automatic_problems')
    op.drop_table('wheel_problems')
    op.drop_table('motor_problems')
    op.drop_table('main_transmission_problems')
    op.drop_table('havac_problems')
    op.drop_table('electrical_problems')
    op.drop_table('brake_problems')
    op.drop_table('body_problems')
    op.drop_table('basic_problems')
    op.drop_table('main_problems')
    op.drop_table('costs')
    # ### end Alembic commands ###
